apiVersion: v1
kind: Service
metadata: 
  name: svc-hello-world-nginx
  labels: 
    app: hello-world-nginx
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    app: hello-world-nginx
  type:  ClusterIP
